version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_net

  user-auth-service:
    build: ./user-auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./user-auth-service/.env
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - app_net

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    env_file:
      - ./product-service/.env
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - app_net

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    env_file:
      - ./order-service/.env
    depends_on:
      - rabbitmq
      - user-auth-service
      - product-service
    restart: on-failure
    networks:
      - app_net

  email-service:
    build: ./email-service
    ports:
      - "5004:5004"
    env_file:
      - ./email-service/.env
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - app_net

  cart-service:
    build: ./cart-service
    ports:
      - "5005:5005"
    env_file:
      - ./cart-service/.env
    depends_on:
      - rabbitmq
      - user-auth-service
      - product-service
    restart: on-failure
    networks:
      - app_net

  payment-service:
    build: ./payment-service
    ports:
      - "5006:5006"
    env_file:
      - ./payment-service/.env
    depends_on:
      - rabbitmq
      - email-service
    restart: on-failure
    networks:
      - app_net

  checkout-service:
    build: ./checkout-service
    ports:
      - "5007:5007"
    env_file:
      - ./checkout-service/.env
    depends_on:
      - rabbitmq
      - cart-service
      - payment-service
      - email-service
    restart: on-failure
    networks:
      - app_net
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - user-auth-service
      - product-service
      - order-service
      - email-service
      - cart-service
      - payment-service
      - checkout-service
    networks:
      - app_net

networks:
  app_net:
    driver: bridge